version: '3'

services:
  mydb:
    image: 'mysql:8.0.31'
    container_name: 'java-mysql'
    environment:
      - 'MYSQL_ROOT_PASSWORD=Qwerasdf1234'
      - 'MYSQL_DATABASE=trains'
      - 'MYSQL_USER=mysql'
      - 'MYSQL_PASSWORD=Qwerasdf1234'
    ports:
      - '3307:3306'

  app:
    container_name: 'java-app'
    ports:
      - 8090:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://java-mysql:3306/trains?autoReconnect=true&useSSL=false
    depends_on:
      - 'mydb'
    build: ./
